// ========================================
// DES Educational Demonstration
// ========================================
//
// NOTE:
// This is an educational symmetric
// encryption demonstration.
// It is NOT the official DES algorithm.
//
// This version safely supports Unicode
// text using TextEncoder and TextDecoder.
// ========================================

// Convert string to Base64 safely

function uint8ArrayToBase64(bytes) {
  let binary = "";

  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }

  return btoa(binary);
}

// Convert Base64 to Uint8Array

function base64ToUint8Array(base64) {
  const binary = atob(base64);

  const bytes = new Uint8Array(binary.length);

  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }

  return bytes;
}

// Generate a numeric key

function simpleHashKey(key) {
  let hash = 0;

  for (let i = 0; i < key.length; i++) {
    hash = (hash << 5) - hash + key.charCodeAt(i);

    hash = hash >>> 0;
  }

  return hash;
}

// Generate repeating key bytes

function generateKeyBytes(key, length) {
  const keyHash = simpleHashKey(key);

  const keyBytes = new Uint8Array(length);

  for (let i = 0; i < length; i++) {
    const shift = (i % 4) * 8;

    keyBytes[i] = (keyHash >>> shift) & 255;
  }

  return keyBytes;
}

// DES Demonstration Encryption

function desEncrypt(text, key) {
  if (!key || key.length < 8) {
    throw new Error("DES key must contain at least 8 characters.");
  }

  // Convert text to bytes

  const encoder = new TextEncoder();

  const textBytes = encoder.encode(text);

  // Generate key bytes

  const keyBytes = generateKeyBytes(key, textBytes.length);

  // XOR transformation

  const encrypted = new Uint8Array(textBytes.length);

  for (let i = 0; i < textBytes.length; i++) {
    encrypted[i] = textBytes[i] ^ keyBytes[i];
  }

  // Convert encrypted bytes
  // to Base64

  return uint8ArrayToBase64(encrypted);
}

// DES Demonstration Decryption

function desDecrypt(cipherText, key) {
  if (!key || key.length < 8) {
    throw new Error("DES key must contain at least 8 characters.");
  }

  try {
    // Convert Base64 to bytes

    const encryptedBytes = base64ToUint8Array(cipherText.trim());

    // Generate same key bytes

    const keyBytes = generateKeyBytes(key, encryptedBytes.length);

    // Reverse XOR operation

    const decrypted = new Uint8Array(encryptedBytes.length);

    for (let i = 0; i < encryptedBytes.length; i++) {
      decrypted[i] = encryptedBytes[i] ^ keyBytes[i];
    }

    // Convert bytes back to text

    const decoder = new TextDecoder();

    return decoder.decode(decrypted);
  } catch (error) {
    throw new Error(
      "Invalid DES ciphertext. Please use ciphertext generated by this application.",
    );
  }
}
